/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Contract, Interface, ContractRunner } from 'ethers';
import type { PositionManager, PositionManagerInterface } from '../PositionManager';

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract ISplitLiquidationCollateral',
        name: 'newSplitLiquidationCollateral',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'AmountIsZero',
    type: 'error',
  },
  {
    inputs: [],
    name: 'BorrowingSpreadExceedsMaximum',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralTokenAddressCannotBeZero',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralTokenAlreadyAdded',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralTokenDisabled',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralTokenNotAdded',
    type: 'error',
  },
  {
    inputs: [],
    name: 'DelegateNotWhitelisted',
    type: 'error',
  },
  {
    inputs: [],
    name: 'FeeEatsUpAllReturnedCollateral',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'fee',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFeePercentage',
        type: 'uint256',
      },
    ],
    name: 'FeeExceedsMaxFee',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidDelegateAddress',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidFeeRecipient',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidMaxFeePercentage',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidPosition',
    type: 'error',
  },
  {
    inputs: [],
    name: 'MaxFeePercentageOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'netDebt',
        type: 'uint256',
      },
    ],
    name: 'NetDebtBelowMinimum',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'newICR',
        type: 'uint256',
      },
    ],
    name: 'NewICRLowerThanMCR',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NoCollateralOrDebtChange',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NothingToLiquidate',
    type: 'error',
  },
  {
    inputs: [],
    name: 'PositionCollateralTokenMismatch',
    type: 'error',
  },
  {
    inputs: [],
    name: 'PriceFeedAddressCannotBeZero',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RedemptionSpreadOutOfRange',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SplitLiquidationCollateralCannotBeZero',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'baseRate',
        type: 'uint256',
      },
    ],
    name: 'BaseRateUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'borrowingSpread',
        type: 'uint256',
      },
    ],
    name: 'BorrowingSpreadUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'collateralAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isCollateralIncrease',
        type: 'bool',
      },
    ],
    name: 'CollateralChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'contract IERC20Indexable',
        name: 'raftCollateralToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'contract IPriceFeed',
        name: 'priceFeed',
        type: 'address',
      },
    ],
    name: 'CollateralTokenAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'contract IERC20Indexable',
        name: 'raftCollateralToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isEnabled',
        type: 'bool',
      },
    ],
    name: 'CollateralTokenModified',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'debtAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isDebtIncrease',
        type: 'bool',
      },
    ],
    name: 'DebtChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'delegate',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'whitelisted',
        type: 'bool',
      },
    ],
    name: 'DelegateWhitelisted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'feeRecipient',
        type: 'address',
      },
    ],
    name: 'FeeRecipientChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'lastFeeOpTime',
        type: 'uint256',
      },
    ],
    name: 'LastFeeOpTimeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'liquidator',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'debtLiquidated',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'collateralLiquidated',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'collateralSentToLiquidator',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'collateralLiquidationFeePaid',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isRedistribution',
        type: 'bool',
      },
    ],
    name: 'Liquidation',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
    ],
    name: 'PositionClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
    ],
    name: 'PositionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'contract IRToken',
        name: 'rToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'contract IERC20Indexable',
        name: 'raftDebtToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'feeRecipient',
        type: 'address',
      },
    ],
    name: 'PositionManagerDeployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'feeAmount',
        type: 'uint256',
      },
    ],
    name: 'RBorrowingFeePaid',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'debtRedeemed',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'collateralSent',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'fee',
        type: 'uint256',
      },
    ],
    name: 'Redemption',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'redemptionSpread',
        type: 'uint256',
      },
    ],
    name: 'RedemptionSpreadUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'contract ISplitLiquidationCollateral',
        name: 'newSplitLiquidationCollateral',
        type: 'address',
      },
    ],
    name: 'SplitLiquidationCollateralChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'totalDebt',
        type: 'uint256',
      },
    ],
    name: 'TotalDebtChanged',
    type: 'event',
  },
  {
    inputs: [],
    name: 'BETA',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_BORROWING_RATE',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_BORROWING_SPREAD',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_REDEMPTION_SPREAD',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MINUTE_DECAY_FACTOR',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_REDEMPTION_SPREAD',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'contract IPriceFeed',
        name: 'priceFeed',
        type: 'address',
      },
    ],
    name: 'addCollateralToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'baseRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'borrowingSpread',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
    ],
    name: 'collateralTokenForPosition',
    outputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feeRecipient',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'debtAmount',
        type: 'uint256',
      },
    ],
    name: 'getBorrowingFee',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getBorrowingRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getBorrowingRateWithDecay',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'collateralAmount',
        type: 'uint256',
      },
    ],
    name: 'getRedemptionFee',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'collateralAmount',
        type: 'uint256',
      },
    ],
    name: 'getRedemptionFeeWithDecay',
    outputs: [
      {
        internalType: 'uint256',
        name: 'redemptionFee',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRedemptionRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRedemptionRateWithDecay',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'delegate',
        type: 'address',
      },
    ],
    name: 'isDelegateWhitelisted',
    outputs: [
      {
        internalType: 'bool',
        name: 'isWhitelisted',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastFeeOperationTime',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
    ],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'collateralChange',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isCollateralIncrease',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'debtChange',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isDebtIncrease',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'maxFeePercentage',
        type: 'uint256',
      },
    ],
    name: 'managePosition',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'position',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'collateralChange',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isCollateralIncrease',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'debtChange',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: 'isDebtIncrease',
        type: 'bool',
      },
      {
        internalType: 'uint256',
        name: 'maxFeePercentage',
        type: 'uint256',
      },
    ],
    name: 'managePosition',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: 'isEnabled',
        type: 'bool',
      },
    ],
    name: 'modifyCollateralToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
    ],
    name: 'priceFeeds',
    outputs: [
      {
        internalType: 'contract IPriceFeed',
        name: 'priceFeed',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rToken',
    outputs: [
      {
        internalType: 'contract IRToken',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
    ],
    name: 'raftCollateralTokens',
    outputs: [
      {
        internalType: 'contract IERC20Indexable',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: 'isEnabled',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'raftDebtToken',
    outputs: [
      {
        internalType: 'contract IERC20Indexable',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'collateralToken',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'debtAmount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxFeePercentage',
        type: 'uint256',
      },
    ],
    name: 'redeemCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'redemptionSpread',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'newBorrowingSpread',
        type: 'uint256',
      },
    ],
    name: 'setBorrowingSpread',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newFeeRecipient',
        type: 'address',
      },
    ],
    name: 'setFeeRecipient',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'newRedemptionSpread',
        type: 'uint256',
      },
    ],
    name: 'setRedemptionSpread',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ISplitLiquidationCollateral',
        name: 'newSplitLiquidationCollateral',
        type: 'address',
      },
    ],
    name: 'setSplitLiquidationCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'splitLiquidationCollateral',
    outputs: [
      {
        internalType: 'contract ISplitLiquidationCollateral',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'delegate',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: 'whitelisted',
        type: 'bool',
      },
    ],
    name: 'whitelistDelegate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class PositionManager__factory {
  static readonly abi = _abi;
  static createInterface(): PositionManagerInterface {
    return new Interface(_abi) as PositionManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PositionManager {
    return new Contract(address, _abi, runner) as unknown as PositionManager;
  }
}
